# Generated by Django 5.0.6 on 2026-06-30 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField(db_index=True)),
                ("project_id", models.UUIDField(db_index=True, null=True)),
                ("environment_name", models.CharField(blank=True, max_length=100)),
                ("actor_type", models.CharField(max_length=50)),
                ("actor_id", models.UUIDField(db_index=True)),
                ("actor_email", models.CharField(blank=True, max_length=255)),
                ("secret_key", models.CharField(blank=True, max_length=500)),
                ("action", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["org_id", "-created_at"], name="idx_audit_org"
                    ),
                    models.Index(
                        fields=["project_id", "-created_at"], name="idx_audit_project"
                    ),
                    models.Index(
                        fields=["actor_id", "-created_at"], name="idx_audit_actor"
                    ),
                ],
            },
        ),
    ]
