# Generated by Django 5.0.6 on 2026-06-30 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_id", models.UUIDField(db_index=True)),
                ("org_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#6366f1", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "environments",
                "ordering": ["name"],
                "unique_together": {("project_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=500)),
                ("encrypted_value", models.TextField()),
                ("iv", models.CharField(max_length=255)),
                ("current_version", models.PositiveIntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by_id", models.UUIDField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="secrets_app.environment",
                    ),
                ),
            ],
            options={
                "db_table": "secrets",
            },
        ),
        migrations.CreateModel(
            name="SecretVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encrypted_value", models.TextField()),
                ("iv", models.CharField(max_length=255)),
                ("version_number", models.PositiveIntegerField()),
                ("created_by_id", models.UUIDField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="secrets_app.secret",
                    ),
                ),
            ],
            options={
                "db_table": "secret_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="secret",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["environment", "key"],
                name="idx_secrets_env_key_active",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="secret",
            unique_together={("environment", "key")},
        ),
        migrations.AddIndex(
            model_name="secretversion",
            index=models.Index(fields=["secret_id"], name="idx_secret_versions_secret"),
        ),
        migrations.AlterUniqueTogether(
            name="secretversion",
            unique_together={("secret", "version_number")},
        ),
    ]
