# Generated by Django 5.0.6 on 2026-06-30 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_id", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("token_hash", models.CharField(max_length=255, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("environment", models.CharField(blank=True, max_length=100)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
