apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envvault-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/envvault.git
    targetRevision: HEAD
    path: infra/helm/envvault
    helm:
      valueFiles:
        - values.yaml
        - values.production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: envvault-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
